name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'


jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.julia-threads }} thread(s) - ${{ github.event_name }}
    runs-on: ubuntu-latest
    env:
      JULIA_NUM_THREADS: ${{ matrix.julia-threads }}
    strategy:
      matrix:
        group:
          - Core
        version:
          - '1' #this will use latest stable v1.x.y version; if break, can go to CI to look at previous successful builds
        julia-threads:
          - '1'

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

  # docs:
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: julia-actions/setup-julia@v3
  #       with:
  #         version: '1.12'

  #     - uses: julia-actions/cache@v2

  #     - name: Instantiate documentation environment
  #       run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

  #     - name: Build documentation
  #       run: julia --project=docs docs/make.jl

  #     - name: Update README
  #       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #       run: |
  #         cp docs/build/README.md README.md
  #         git config user.name "github-actions[bot]"
  #         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #         git add README.md
  #         git diff --cached --quiet || git commit -m "Update generated README [skip ci]"
  #         git push
